### ISSUE TITLE
Question: Extended WiFi Connection

### ISSUE THREAD

**Issue by benni336** [christianh17/ioBroker.bydhvs#100]
Hi, 
I am looking around for some tooling to read my HVM with ModBus. Unfortunately I could not yet find any docs about that but I found your project on [photovoltaikforum](https://www.photovoltaikforum.com). 

Before going into further details I would like to ask, how you connect to the battery. You state that you use the WiFi of the battery. But that should turn off after x minutes. Is there any way to use the ethernet connection? What do you do to stay connected?

Best Ben

**Comment by christianh17** [comment]
Hi! I use the ethernet connection. You should follow this link  https://www.photovoltaikforum.com/thread/150898-byd-hvs-firmware-update/?postID=2215343#post2215343 (it's German but I am sure you will use a translator) User Becker3 has a very good documentation how to reach the battery via ethernet.
