### ISSUE TITLE
Error Fehler

### ISSUE THREAD

**Issue by Trunks1982** [christianh17/ioBroker.bydhvs#105]
Hi in meinem Log kommt immer dieser Fehler siehe Bild.
Ich habe einen HVM Speicher mit dem der Adapter soweit auch funktioniert.

![Bildschirmfoto 2022-02-24 um 13 36 43](https://user-images.githubusercontent.com/62701386/155525265-74644e62-2ea0-4a75-a9ab-a1bfeaf6d0c9.png)
.

**Comment by christianh17** [comment]
Das ist komisch, ich kann das mit meinen Tests leider nicht nachvollziehen. Kannst Du bitte mal den Log-Modus auf "Silly" setzen und zusätzlich in den Settings des Adapters den Testmodus aktivieren? Dann das Log herunterladen (nicht per Copy und Paste kopieren, dann fehlen Daten). Mit dem Log kann ich dann auf die Suche nach dem Fehler gehen.
Viele Grüße

**Comment by Trunks1982** [comment]
[iobroker.2022-02-26.log](https://github.com/christianh17/ioBroker.bydhvs/files/8145313/iobroker.2022-02-26.log)

Hi ich hoffe das hilft dir weiter.
Gruß Christoph

**Comment by christianh17** [comment]
Danke, habs gefunden. Ich habe dieses logging auf info heruntergestuft. Kommt in der nächsten Version. Es gibt gleich ein commit, dann wäre es zunächst nur in der Version bei github, ich hoffe es finden sich einige Tester dafür.

**Comment by Trunks1982** [comment]
werde es testen

**Comment by christianh17** [comment]
Danke!

**Comment by Trunks1982** [comment]
Fehler scheint nicht mehr zukommen.Bis jetzt kein Eintrag mehr im Log.
