### ISSUE TITLE
Entlade Wert

### ISSUE THREAD

**Issue by Trunks1982** [christianh17/ioBroker.bydhvs#126]
Hi mir ist aufgefallen wenn ich per Modbus den Batteriewechselrichter abfrage ein Unterschied zu deinem Adapter im schlimmsten Fall bis zu 40w unterschied besteht.Den Modbus Wert habe ich mit dem Sunnyportal verglichen und dieser war identisch.
Bitte überprüf das bitte mal.
Gruss Christoph

**Comment by christianh17** [comment]
Hi Christoph!

Verstehe ich das richtig? Die Diskrepanz besteht beim Laden der Daten aus dem Wechselrichter vs. der Daten aus der Batterie? Wenn ja: Gibt es einen immer gleichen Unterschied oder schwankt das Delta?

Viele Grüße
Christian

**Comment by christianh17** [comment]
Ich schließe den Issue, wenn erforderlich: Bitte neu eröffnen.
