### ISSUE TITLE
Abfrage über Node-Red

### ISSUE THREAD

**Issue by Becker884** [christianh17/ioBroker.bydhvs#206]
Hallo,
kann ich den BYD irgendwie über Node-Red abfragen ?
min/max Spannungen würden mir schon reichen.

**Comment by christianh17** [comment]
Sorry, da müsstest Du Dich bitte ans Forum wenden. Es gibt einen Node Red Adapter im ioBroker aber ob dieser die States abfragen und damit etwas "anfangen" kann: Da bin ich überfragt.
