### ISSUE TITLE
version 1.4.1 is not in io-package

### ISSUE THREAD

**Issue by arteck** [christianh17/ioBroker.bydhvs#210]
check you io-package version number

![grafik](https://github.com/christianh17/ioBroker.bydhvs/assets/6681528/5491833c-23c5-47a6-870d-81e293e5b1fc)

**Comment by christianh17** [comment]
Done, no we have 1.4.2 and hopefully everything will work.

**Comment by christianh17** [comment]
Done, no we have 1.4.2 and hopefully everything will work.
