### ISSUE TITLE
Wrong typ nach Umstellung auf js-controller 3.3.4

### ISSUE THREAD

**Issue by JBSullivan** [christianh17/ioBroker.bydhvs#23]
lt. Community sollen Meldungen die sich aus der Umstellung des js-controller auf die Version 3.3.4 ergeben bei den entsprechenden Adaptern gemeldet werden.

Der Adapter funktioniert Augenscheinlich normla, jedoch wird das LOG mit WARN Meldungen übersäät.

![image](https://user-images.githubusercontent.com/44617472/116776362-55ef5100-aa68-11eb-88d8-977c9d8a1eb8.png)

**Comment by christianh17** [comment]
Hi!
Ist in Arbeit, gibt eine neue Version mit neuen Features und der Punkt ist dann auch mit behoben.

**Comment by christianh17** [comment]
solved with new version
