### ISSUE TITLE
Lower poll interval limit below 60 seconds?

### ISSUE THREAD

**Issue by protree** [christianh17/ioBroker.bydhvs#277]
Is there a reason why the poll interval is limited to 60 seconds? I manually decreased it down to 15 seconds and it seems to run stable despite some random connection errors (Error connecting to 192.168.XXX.XXX) that occur every few minutes. The only downside of those connection errors that I can see is that some polls are missed but this is better than having an update only every 60 seconds. The adapter seems to runs stable even though.

Is there any known risk to damage/overload the battery when decreasing the poll interval?

relevant code:
https://github.com/christianh17/ioBroker.bydhvs/blob/55d06a849a015b35995e8e3fdc3c35f57fdd9c0d/main.js#L1174-L1177

EDIT: 15 seconds, not 5...

**Comment by christianh17** [comment]
I have no idea if this can harm the battery. The code is already changed - you get only a warning and it is not reset to 60. So I close the issue.
