### ISSUE TITLE
Wrong name for Diagnosis.BatteryVolt and other mistakes in the object structure "Diagnosis"

### ISSUE THREAD

**Issue by zloe** [christianh17/ioBroker.bydhvs#309]
The "name" for the state Diagnosis.BatteryVolt is "Wirkungsgrad of that tower"

**To Reproduce**  
Open object browser and view the objects

**Expected behavior**  
The name should read something like "Voltage of Battery"

**Screenshots & Logfiles**  
![image](https://github.com/user-attachments/assets/1cfa7cfd-408b-420f-93a2-3871ec2107b3)

**Versions:**  
 - Adapter version: Version from github (1.5.1?)
 - JS-Controller version: 6.0.9
 - Node version: 19.9.0
 - Operating system: Linux/Raspian

**Comment by christianh17** [comment]
Kümmere mich drum, siehe auch Kommentar im PR

**Comment by christianh17** [comment]
repaired in github, will be published in new version, thx for the hint!
