### ISSUE TITLE
Nach BYD Firmware Update (BMS V3.23-B) keine Diagnosedaten

### ISSUE THREAD

**Issue by JBSullivan** [christianh17/ioBroker.bydhvs#66]
Heute gab es ein BMS Update (V3.23-B) des Speichers. Adapter Version ist 1.2.3

Mein Speicherturm hat 4 Elemente. Lt. Instanz Beschreibung sollten mit 4 Elementen die Diagnose Daten abrufbar sein.
Das hat in der Vergangenheit auch schon funktioniert.

Wenn man jetzt den Objekt Baum aufklappt, ist der Diagnosis Ordner leer.

![image](https://user-images.githubusercontent.com/44617472/136672835-dce49001-e912-4cf2-b9f4-d891a447963a.png)

**Comment by christianh17** [comment]
Kannst Du mir bitte einmal das Log schicken? Der Test-Modus muss angestellt sein (in der Instanzen-Konfiguration). Und: Die Log-Datei nicht per Copy und Paste herauskopieren, dann fehlen Teile. Ich bräuchte das Download der Logs.
Du kannst mir die Daten gerne auch per Mail schicken wenn Du sie hier nicht posten möchtest - in den Daten befindet sich auch die Seriennummer des Speichers.
Dann werfe ich wieder meinen "Speichersimulator" an und schaue wo das Problem ist.

**Comment by christianh17** [comment]
Die Mail-Adresse möchte ich hier nicht noch einmal schreiben, dann bekomme ich noch mehr Spam. Aber: Du findest sie in der readme.md des Adapters im "License"-Teil. Eigentlich kann ich mir das nicht erklären. Hast Du denn beim Rollback die Datenpunkte gelöscht? Wenn nicht sollten ja zumindestens die alten Werte noch vorhanden sein. Bin auf das Log gespannt.
