### ISSUE TITLE
Vorschlag - SoH als neuer Datenpunkt 

### ISSUE THREAD

**Issue by JBSullivan** [christianh17/ioBroker.bydhvs#67]
Das ist kein Issue, sondern nur ein Vorschlag für einen weiteren Datenpunkt, sofern das machbar ist.

Ich vermute du hast über das BeConncet Plus Tool als Admin Zugriff auf den Speicher. In der LOG Ebene werden ja sehr kryptische Meldungen generiert, welche man, sofern Excel installiert ist, in Klartext mit dem integrierten Translation Tool übersetzen kann.

Dabei kommt dann so etwas dabei heraus.  Darin ist dann der Wert für den SoH - State of Health - also die Akku "Gesundheit" enthalten. Das wäre ganz cool wenn man den Datenpunkt Wert auch über ioB abgreifen bzw. in einer VIS Sichtbar machen könnte.

![image](https://user-images.githubusercontent.com/44617472/137601548-96637052-6a3f-41ec-b6bb-0d9d4ccabf75.png)

**Comment by christianh17** [comment]
Die Idee ist gut, das hätte ich auch gerne für mich und würde es gerne in meinen Adapter integrieren. Voraussetzung natürlich: Ich bekomme irgendwie heraus wie ich an die Daten herankomme. Ich scheitere aber schon am ersten Punkt, ich finde das Translation Tool nicht - ggfs. nur Tomaten auf den Augen. Kannst Du mir kurz einen Tipp geben wie man da hinkommt?

**Comment by JBSullivan** [comment]
<quote>Kannst Du mir kurz einen Tipp geben wie man da hinkommt?</quote>

Ja, gerne -  ich gehe mal davon aus, das du auch BeConnect Plus 1.61 verwendest? Am Anfang kommt ein LogIn Fenster, wo man verschiedene Nutzer Level auswählen kann.

Hier den Admin auswählen. Da du genauso wie ich, das Passwort für den Admin nicht kennen, einfach im BeConnect Ordner auf dem PC die config.ini, gemäß dem Muster unten abändern. Dann hast du Zugriff auf alle Benutzer Level.

Erst dann tun sich im Menü neue Untermenüs auf. Das Translaten funktioniert aber nur, wenn Excel auf deinem PC wo auch BeConnect läuft, installiert ist. Ohne Excel stürzt das Programm ab.

Dann exportierst du dir die BMU & BMS History Dateien und lädst sie anschließend wieder als Files unter dem Menüpunkt "Translation" rein.

Dann werden aus den kryptischen Zahlenkolonnen, richtige Texte so wie in meinem Screenshot auf GIT.

![image](https://user-images.githubusercontent.com/44617472/137631067-ca7da24b-d24f-4d10-9c67-7f27c546fbaf.png)

![image](https://user-images.githubusercontent.com/44617472/137631290-178d52e3-6c9c-463c-8707-d6fc8b8ae97e.png)




[A]
1=""
2=""
3=""
4=""

[B]
1=""
2=""
3=""
4=""

[C]
1=""
2=""
3=""
4=""

[D]
1=""
2=""
3=""
4=""

[E]
1=""
2=""
3=""
4=""

**Comment by christianh17** [comment]
Hi! Gute Nachrichten, ich glaube ich habe den SOH in den Standard-Rohdaten gefunden :-). Ich versuche in den nächsten Tagen eine neue Version zu erstellen in der das enthalten ist.

**Comment by JBSullivan** [comment]
👍👍👍👍

**Comment by christianh17** [comment]
Hi! Im Github ist jetzt die neue Version mit SOH als Datenpunkt, magst Du mal testen ob es bei Dir auch funktioniert? Wenn es bei Dir auch klappt geht es auch als neue Version ins NPM. Wie Du von Github installieren kannst, weißt Du, oder?

**Comment by JBSullivan** [comment]
Yup kann ich machen. Taucht der neue DP nach dem Update einfach in der Objekt Liste auf? Klar Aktualisierung nach GIT Install ist klar.

**Comment by JBSullivan** [comment]
PERFEKT 👍👍

![image](https://user-images.githubusercontent.com/44617472/140103518-34ea9a99-ab8a-42b7-a440-64bfb726d477.png)

**Comment by christianh17** [comment]
Du bist schneller als ich antworten kann. Danke für den Test und die Bestätigung. Jetzt muss ich nur noch irgendwie die Meldungen aus den automatisierten Tests hübsch bekommen und dann geht die Version public.

**Comment by christianh17** [comment]
done
