### ISSUE TITLE
Neuer Vorschlag :D - Zykluszahl

### ISSUE THREAD

**Issue by JBSullivan** [christianh17/ioBroker.bydhvs#75]
Sorry, wenn ich nerve und mit immer neuen Ideeen um die Ecke komme 😎 - ich habe im Photovoltaik Forum gelesen, das Wechselrichter von SMA Solar & Kostal die Zykluszahlen der Speicher Ladungen ausgeben.

Diese Daten stellt allerdings nicht BYD bereit, sondern die werden aus Ladung/Entladung errechnet. Du hast ja auch die beiden Datenpunkte bydhvs.0.State.Power_Consumption und bydhvs.0.State.Power_Delivery integriert. Ließe sich damit nicht auch so etwas wie ein Ladezyklus errechnen?

Für "Späteinsteiger" müsste in der Instanz dann noch die Möglichkeit gegeben sein, das man seine Zyklen "bis dato" eintragen kann. Die mus sich aber jeder selber errechnen (vielleicht in der Adapter Beschreibung ein kleiner Hinweis WIE man das Rückwirkend errechnen kann)

...... wie gesagt, nur so eine Idee und evtl. Nice to have

PS: Es gibt im PV Forum auch ein Perl Skript, was wohl auch die Zyklen (abholt?) berechnet. Vielleicht ist das ein Ansatz für dich.

https://www.photovoltaikforum.com/thread/150898-byd-hvs-firmware-update/?postID=2248716&highlight=readBYD.pl#post2248716

**Comment by christianh17** [comment]
Hi! Um Ehrlich zu sein: Das sehe ich nicht als Datenpunkt. Bei SMA und Kostal kommt das aus dem Wechselrichter und wenn man möchte: So etwas lässt sich easy mit Javascript oder Blockly im ioBroker "zaubern". Den Algorhitmus könnte ich sowieso nicht allen "recht" machen.
